### ISSUE TITLE
Highlight content in different languages 

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium.io#120]
As the Cilium community grows around the world, we should add something to the cilium.io page to highlight certain languages and possibly add filters for it

**Comment by divz-codess** [comment]
Hi @xmulligan can you please elaborate as to what all features you would like to have and in which languages ?

**Comment by xmulligan** [comment]
@divz-codess this is more of an umbrella issue as we haven't figured out yet what features or languages we want yet. I think it will become more apparent once we start working on https://github.com/cilium/cilium/issues/20182

**Comment by xmulligan** [comment]
I think this issue is a little too broad to really be effective so closing for now. We should come back to this with more concrete proposals to help support the growing Cilium community around the globe though.
