### ISSUE TITLE
Can't build site locally - GRAPHQL error due to missing HubspotEmails

### ISSUE THREAD

**Issue by chalin** [cilium/cilium.io#165]
Hi. It would be great if contributors could build the website locally. The instructions in the README don't work for me. So far, I've discovered that I need to `export GATSBY_DEFAULT_SITE_URL=http://localhost`, but even then, I'm getting this error:

```console
$ npm run build

> cilium.io@0.1.0 build
> gatsby build

success compile gatsby files - 1.708s
...
success onPreExtractQueries - 0.002s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "objects" on type "HubspotEmails".

If you don't expect "objects" to exist on the type "HubspotEmails" it is most likely a typo. However, if you expect "objects" to exist there are a couple of
 solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config, please try a restart of your development server.
- You want to optionally use your field "objects" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.

File: src/components/pages/newsletter/issues/issues.jsx:16:9

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 55.484s
failed extract queries from components - 5.402s
```

Maybe I need a bogus `HUBSPOT_API_KEY`, or some code changes might be required to allow that query to fail?

/cc @caniszczyk @nate-double-u

**Comment by chalin** [comment]
Hi @cilium/docs-structure @tgraf @liquidat @xmulligan: I'd like to make progress on #164, but it'll be a bit harder to do so if I can't build the site locally to validate my changes. Can someone help out? Thanks!

**Comment by vannyle** [comment]
Hi @chalin, unfortunately, `HUBSPOT_API_KEY` is a sensitive credential, and I can share it with you publicly. To build the project locally, I’d suggest commenting the related [piece of code](https://github.com/cilium/cilium.io/blob/main/gatsby-node.js#L187-L202) and the component [Issues](https://github.com/cilium/cilium.io/blob/main/src/components/pages/newsletter/issues/issues.jsx#L14). 
Or please just ignore the error by closing the window after building. 
![image](https://user-images.githubusercontent.com/48465000/200032496-398ba31e-7406-404b-b90f-daaa6279b11c.png)

**Comment by vannyle** [comment]
The issue has been fixed with https://github.com/cilium/cilium.io/pull/198

**Comment by chalin** [comment]
Nice, thanks for letting me know.
