### ISSUE TITLE
Post Google Analytics 4 (GA4) migration cleanup

### ISSUE THREAD

**Issue by chalin** [cilium/cilium.io#194]
Followup to:

- #164

Tasks:

- [ ] Drop GTM ID setup code: https://github.com/cilium/cilium.io/blob/dd2a0a77bd96717582c5a9a1d0f8e5294235b71e/gatsby-config.js#L142
    CNCF does't have access to the GTM account, so I'm (@chalin) unsure how you have things setup. If you've registered UA IDs, those will stop working in 2023. We can [connect] the UA ID from the GA4 web data-stream if necessary, if we want to remove the GTM ID setup code now but keep receiving events between now and their EOL.

**Comment by xmulligan** [comment]
@chalin is this still relevant? I think CNCF has access to the tag now

**Comment by chalin** [comment]
Hi @xmulligan - AFAIK, the CNCF does not have access to the GTM account that manages [GTM-M533ZSF](https://github.com/cilium/cilium.io/blob/dd2a0a77bd96717582c5a9a1d0f8e5294235b71e/gatsby-config.js#L142).

In any case, I just checked using the Google Tag Assistant, and the GTM ID no longer seems to be active, so yes, we can close this issue.
