### ISSUE TITLE
 rephrasing point no.3 in getting started of the contribution guide.

### ISSUE THREAD

**Issue by Oms-343** [cilium/cilium.io#244]
hello maintainers,  I was implementing the steps to run cilium.io website on localhost and thus make some changes. But i really stumbled upon this.
![image](https://user-images.githubusercontent.com/98374339/219285952-0f044c11-16dd-4b51-a66a-a4cb5b48bab0.png)

the 3rd point says "Copy .env.example and rename it into .env" but what to copy at the first place.. I think it should just be 
 "rename.env.example to.env."  just my opinion. thankyou 😊

**Comment by xmulligan** [comment]
@zacharysarah is that correct?

**Comment by Neilblaze** [comment]
Although it's just a typo, but nice catch!  @xmulligan we can update that to "Rename `.env.example` into `.env`"

**Comment by thebsdbox** [comment]
It's confusing language.. but I presume the example command `cp .env.example .env` would suffice?

**Comment by Neilblaze** [comment]
@thebsdbox I also think so 😅

**Comment by Oms-343** [comment]
> It's confusing language.. but I presume the example command `cp .env.example .env` would suffice?

Yes correct,  we can add this command to the readme inside that 3rd point so that no one will have even a slight doubt in setting the project locally?

**Comment by xmulligan** [comment]
Sure, please do

**Comment by Oms-343** [comment]
@xmulligan I would love to.. Thankyou👍

**Comment by Neilblaze** [comment]
@Oms-343 I've created a PR (#249) & have added you as a co-author!
