### ISSUE TITLE
[Urgent] Opt-out of "Automatically set up a basic Google Analytics 4 property"

### ISSUE THREAD

**Issue by chalin** [cilium/cilium.io#248]
In March (next week), Google will start creating new GA4 site tags if there's no existing GA4 ID connected to an existing UA ID. But Cilium.io already has a GA4 property.

1.  So, Cilium.io needs to **opt out of Google's forced & automatic GA4 migration**. To do so:

    - Visit the UA `UA-96283704-1` [Google Analytics 4 Property Setup Assistant](https://analytics.google.com/analytics/web/?pli=1#/a96283704w141907308p146451474/admin/ga4-setup-assistant) panel, and 
    - Turn off **Automatically set up a basic Google Analytics 4 property**

    Unfortunately, I have access to the panel but I don't have the permissions to opt out. Can you either grant me the permissions or make the change? 

2. Note that according to the Google Tag Assistant, the Cilium docs are also being tracked via another UA property with ID `UA-17997319-1`. I don't have access to that account. You'll need to opt out of there too.

3. If you have access to the ReadTheDocs account for the Cilium docs, it might be a good idea to **remove the UA IDs** from the config there.

For context regarding the GA4 opt-out issue, see:

- https://github.com/cncf/techdocs/issues/170

/cc @nate-double-u @lizrice @qmonnet

**Comment by qmonnet** [comment]
I don't have access to these.

@xmulligan Hi, do you have access and required permissions in the Google Analytics panel to help? Otherwise, do you know who does?

Cc @aanm regarding item 3 and access to ReadTheDocs

**Comment by chalin** [comment]
Thanks @lizrice. 

> I can't see any properties with the ID `UA-17997319-1` in the admin panel. I wonder if this ID is some kind of default value in a Sphinx config file that has been propagated inadvertently?

In that case, would it be possible to remove that ID from the Sphinx config?

**Comment by qmonnet** [comment]
@chalin Do you mean the `googleanalytics_id` variable in Documentation/conf.py should be gone altogether? I suppose this means the ID we use is defined somewhere in that case?

I can take care of the removal from conf.py if that's what we need

**Comment by chalin** [comment]
> @chalin Do you mean the `googleanalytics_id` variable in Documentation/conf.py should be gone altogether?

No, that stays.

What needs to be removed is the UA ID set for `global_analytics_code` in the RTD config, e.g.:

```python
context = {
    ...
    'user_analytics_code': '',
    'global_analytics_code': 'UA-17997319-1',
   ...
}
```

Change the setting to `'global_analytics_code': ''` (or drop the both analytics parameters if that works).

**Comment by chalin** [comment]
Since we're talking about require changes, there is this that needs to be done:

- #194

**Comment by aanm** [comment]
I've removed `UA-96283704-1` from the readthedocs admin panel

**Comment by chalin** [comment]
@aanm or @lizrice can you remove `UA-17997319-1` from the config too?

**Comment by aanm** [comment]
@chalin I don't see the `UA-17997319-1` anywhere in the readthedocs admin panel nor we do have that set in our Documentation config

**Comment by chalin** [comment]
@aanm - thanks for confirming. Investigating this a bit more, it seems to be a RTD ID, so we're good! Thanks all!

**Comment by xmulligan** [comment]
Thanks for your help @chalin !
