### ISSUE TITLE
Missing link(s) to video/doc 

### ISSUE THREAD

**Issue by peterj** [cilium/cilium.io#264]
I noticed the following text on the main page (Security > Advanced Network Policy item) without any links:

```text
Get started here or watch a video to learn more.
```

I can make a fix to add the links, but I am unsure what the intended link targets were here.

**Comment by xmulligan** [comment]
Thanks for pointing this out. However, we will be updating this section with #226 so I wouldn't want you to have to do some work that is going to be removed soon :)
