### ISSUE TITLE
Highlight end users and industries

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium.io#269]
It would be great to highlight the adopters by moving that to the nav bar and maybe creating pages for specific industries that Cilium is helpful in

**Comment by xmulligan** [comment]
Verticals I am thinking right now:

- [ ] Media/Telecommunications
- [ ] Financial Services
- [ ] Consulting
- [ ] SaaS/Software
- [ ] Cloud Provider
- [ ] Retail

**Comment by xmulligan** [comment]
We could make pages similar to https://www.hashicorp.com/industries/financial-services

**Comment by paularah** [comment]
![image](https://github.com/cilium/cilium.io/assets/37967706/2c1c760c-e9c1-4dd0-b0f6-1263a58e0a32)

I imagine this would look like "learn" navbar, with verticals for each industry and corresponding pages?

**Comment by xmulligan** [comment]
I think we could actually do it as a drop down under Use Cases now that it is there

**Comment by kirtanchandak** [comment]
Hey, @xmulligan do we need to design the pages before starting the development?

**Comment by xmulligan** [comment]
Hey @kirtanchandak sorry @paularah is already working on this, I just forgot to assign him until now

**Comment by xmulligan** [comment]
I've discussed with @paularah and we've come up with these categories

Financial services 
Media and Entertainment 
Telcos and Data center providers
Cloud providers (emphasis on hyper-scale clouds)
Consulting 
Cyber security - (emphasis on tetragon and cilium security features)
SaaS/Software/DBaaS
E-commerce

**Comment by xmulligan** [comment]
closed with #343
