### ISSUE TITLE
Improve fallback landing page

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium.io#376]
Similar to https://github.com/ebpf-io/ebpf.io-website/issues/383, cilium.io seems to have some legacy code for the 404 page, that is, well, not optimal (`the sadaaaaaness`??):

![image](https://github.com/cilium/cilium.io/assets/17001771/468d30e0-10cd-4da8-b4fb-2824fe386126)

Could we find something nice instead?

**Comment by xmulligan** [comment]
closed with #390
