### ISSUE TITLE
Edge Computing Industry Vertical page

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium.io#396]
The use of Cilium on the edge is growing. It would be great to have a page to cover this

**Comment by xmulligan** [comment]
Maybe use https://www.redhat.com/en/technologies/device-edge for inspiration

**Comment by shivam-Purohit** [comment]
@xmulligan can I be any help on this?

**Comment by xmulligan** [comment]
I don't think we have enough content for this page yet, but hopefully soon

**Comment by shivam-Purohit** [comment]
> I don't think we have enough content for this page yet, but hopefully soon

sure! I was looking to contribute to this project to learn more about it. Can you guide me on how to get started?

**Comment by xmulligan** [comment]
I would check out the contributor guide https://docs.cilium.io/en/stable/contributing/development/

**Comment by xmulligan** [comment]
I would go ask on that issue

**Comment by xmulligan** [comment]
this might be useful https://kubeedge.io/blog/enable-cilium/

**Comment by xmulligan** [comment]
closed with #536
