### ISSUE TITLE
Ambient mesh statement should be modified when istio 1.21 is out

### ISSUE THREAD

**Issue by linsun** [cilium/cilium.io#446]
Specific text below:

The new experimental [ambient mesh](https://istio.io/latest/blog/2022/introducing-ambient-mesh/) data plane is not supported, as it interferes with the Cilium data plane.

**Comment by linsun** [comment]
Target ETA for istio 1.21 is mid Feb.

Refer to this blog for details. https://istio.io/latest/blog/2024/inpod-traffic-redirection-ambient/

cc @kdorosh

**Comment by xmulligan** [comment]
the docs live in cilium/cilium. Did you mean to make this issue over there?

**Comment by linsun** [comment]
yep, my bad - didn't check before I open, typically website is hosted in .io repo.

**Comment by linsun** [comment]
Updated already - https://github.com/cilium/cilium/pull/31525
