### ISSUE TITLE
Feature Request - add corresponding routing traffic for network policy example

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium.io#477]
Here is the documentation to allow a service to route traffic to a service in another cluster https://docs.cilium.io/en/stable/network/clustermesh/policy/#gs-clustermesh-network-policy

however, documentation to routing traffic to a specific service in another cluster seems evasive, there is docs for same service in multi cluster but looking for routing one service traffic to another cluster as shown in the network policy.

**Comment by xmulligan** [comment]
Thanks for opening this issue, however the docs are hosted in the main Cilium repo https://github.com/cilium/cilium. Can you create the issue over there so it is tracked properly?
